# This is a basic workflow that is manually triggered

name: Build Image

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Generate version.json
        run: ./versions.sh
